### ISSUE TITLE
Fails to install on Termux

### ISSUE THREAD

**Issue by edshamis** [astral-sh/ruff-lsp#112]
❯ pip install --user ruff-lsp
Collecting ruff-lsp
  Using cached ruff_lsp-0.0.27-py3-none-any.whl (11 kB)
Collecting lsprotocol>=2023.0.0a1 (from ruff-lsp)
  Using cached lsprotocol-2023.0.0a1-py3-none-any.whl (69 kB)
Collecting pygls>=1.0.1 (from ruff-lsp)
  Using cached pygls-1.0.1-py3-none-any.whl (40 kB)
Collecting ruff>=0.0.267 (from ruff-lsp)
  Using cached ruff-0.0.267.tar.gz (1.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      error: failed to get `ruff` as a dependency of package `ruff_cli v0.0.267 (/data/data/com.termux/files/usr/tmp/pip-install-3b_k6s5l/ruff_47f73d9b13cc46e2b1aa33cd8a95cf41/crates/ruff_cli)`

      Caused by:
        failed to load source for dependency `ruff`

      Caused by:
        Unable to update /data/data/com.termux/files/usr/tmp/pip-install-3b_k6s5l/ruff_47f73d9b13cc46e2b1aa33cd8a95cf41/local_dependencies/ruff

      Caused by:
        failed to parse manifest at `/data/data/com.termux/files/usr/tmp/pip-install-3b_k6s5l/ruff_47f73d9b13cc46e2b1aa33cd8a95cf41/local_dependencies/ruff/Cargo.toml`

      Caused by:
        error inheriting `colored` from workspace root manifest's `workspace.dependencies.colored`

      Caused by:
        failed to find a workspace root
      💥 maturin failed
        Caused by: Cargo metadata failed. Does your crate compile with `cargo build`?
        Caused by: `cargo metadata` exited with an error:
      Error running maturin: Command '['maturin', 'pep517', 'write-dist-info', '--metadata-directory', '/data/data/com.termux/files/usr/tmp/pip-modern-metadata-m8_1bl32', '--interpreter', '/data/data/com.termux/files/usr/bin/python3']' returned non-zero exit status 1.
      Checking for Rust toolchain....
      Running `maturin pep517 write-dist-info --metadata-directory /data/data/com.termux/files/usr/tmp/pip-modern-metadata-m8_1bl32 --interpreter /data/data/com.termux/files/usr/bin/python3`
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by konstin** [comment]
Reported upstream: https://github.com/PyO3/maturin/issues/1609

**Comment by konstin** [comment]
This should be fixed with the latest release, could you retry?

**Comment by konstin** [comment]
> ld.lld: error: unable to find library -lgcc

That looks like a problem with your linker, but i unfortunately don't understand enough about aarch64-linux-android to help you debug. Can you `cargo build` a git clone of ruff?

**Comment by konstin** [comment]
In that case i'm afraid we can't do much on ruff's side :/

**Comment by JonathanPlasse** [comment]
Should not wheels be available to avoid compiling ruff?

**Comment by konstin** [comment]
as far as i know pypi doesn't support aarch64-linux-android

**Comment by FreddieOliveira** [comment]
What if I already have ruff binary in my PATH? How can I tell `pip install ruff-lsp` that it doesn't need to compile it again?
