### ISSUE TITLE
Plugin was infected by a virus

### ISSUE THREAD

**Issue by duytrung** [astral-sh/ruff-lsp#134]
Hello,

I found the plugin was infected with a virus, scanned by Bitdefender. Not sure if it was a false alarm.

![image](https://github.com/charliermarsh/ruff/assets/2046672/03018f5d-b2ac-4663-b1b4-ea228db7fb61)

As Bitdefender suggested, I have to rescan and restart the computer:

![image](https://github.com/charliermarsh/ruff/assets/2046672/46515390-aa02-4d1a-b6b6-1cdc9072ee26)

Thanks for considering the issue

**Comment by kuator** [comment]
Hoping, it's not Corona

**Comment by charliermarsh** [comment]
I don't see much actionable here unfortunately, in the absence of more info.
