### ISSUE TITLE
Implement support for linting on change

### ISSUE THREAD

**Issue by karthiknadig** [astral-sh/ruff-lsp#280]
This is one of the most asked for features in python extension: https://github.com/microsoft/vscode-python/issues/408

**Comment by dhruvmanila** [comment]
I think we already support this using the following setting:

```
lint.run = "onType"
```

And in VSCode,

```json
{
	"ruff.lint.run": "onType"
}
```

Closing this as completed but let me know if you meant something else :)

**Comment by karthiknadig** [comment]
That is perfect.
