### ISSUE TITLE
neovim: `vim.lsp.buf.format()` to run `ruff format` on current buffer?

### ISSUE THREAD

**Issue by smackesey** [astral-sh/ruff-lsp#288]
I was assuming this would work because:

- The Ruff VSCode extension now acts as a formatter (as distinct from being able to autofix)
- The Neovim instructions show:

```
vim.keymap.set('n', '<space>f', function() vim.lsp.buf.format { async = true } end, bufopts)
```

However it does not work. Is there something that needs to be passed as an initialization option (since I know the formatter needs to be explicitly enabled in VSCode).

**Comment by charliermarsh** [comment]
We check for an `RUFF_EXPERIMENTAL_FORMATTER` environment variable on startup:

```python
RUFF_EXPERIMENTAL_FORMATTER = bool(os.environ.get("RUFF_EXPERIMENTAL_FORMATTER", False))
```

We're planning to remove it this coming week, but in the interim, can you try setting that and see if it works as expected?

**Comment by smackesey** [comment]
ok cool it works with that env var set!

**Comment by smackesey** [comment]
Is any similar manual intervention needed to make formatting work for the sublime extension? We have at least one dev using sublime.

**Comment by charliermarsh** [comment]
Do you know if they're using this? https://github.com/sublimelsp/LSP-ruff Or something else? (Not certain, need to look into it so want to make sure I'm investigating the right thing.)
