### ISSUE TITLE
Use narrow edits when possible

### ISSUE THREAD

**Issue by karthiknadig** [astral-sh/ruff-lsp#290]
When I created the template for LSP servers, I had use broad edit you see being used here:
https://github.com/astral-sh/ruff-lsp/blob/0bb19b4f56e2c99c7651ac391a964a1c8e59ffa5/ruff_lsp/server.py#L760-L790

The reason is that, IDEs tend to move the cursor based on the edits. Some times the broad edit moves the cursor to the bottom of the file. Users have complained on the black extension and autopep8 extension that this was disruptive.

I recommend using broad edits only when the diff computing takes too long, use narrow edits when possible. Here is an implementation for calculating edits, that takes time out into consideration:
https://github.com/microsoft/vscode-black-formatter/blob/main/bundled/tool/lsp_edit_utils.py

Since you own the formatter, I highly recommend exposing the computed diffs from the formatter itself as JSON, that you can quickly convert to `TextEdit`s. For reference, `difflib.SequenceMatcher` can take several minutes to calculate diff on this test case:

*unformatted*: https://github.com/microsoft/vscode-black-formatter/blob/main/src/test/python_tests/test_data/sample3/sample.unformatted
*formatted*: https://github.com/microsoft/vscode-black-formatter/blob/main/src/test/python_tests/test_data/sample3/sample.py

I recommend adding the above test case to your suite.

/cc @charliermarsh

**Comment by charliermarsh** [comment]
Interesting! So you're saying that narrow edits provide a better user experience (since they won't move the cursor), at the cost of performance (the diffs can be expensive to compute) -- is that right?

**Comment by karthiknadig** [comment]
> So you're saying that narrow edits provide a better user experience (since they won't move the cursor), at the cost of performance (the diffs can be expensive to compute) -- is that right?

That is correct

**Comment by karthiknadig** [comment]
This will also allow you to implement Range Formatting, and support format on type (which is a variant of range formatting)

**Comment by zanieb** [comment]
Hm @konstin was working on range formatting for use in the LSP but I don't know if this was explored.

**Comment by karthiknadig** [comment]
Sorry for spamming with too many notifications.

The https://pypi.org/project/Levenshtein/ package for diff computation is really fast, it is about 100 times faster than the `difflib` which is pure python implementation. If `ruff-lsp` adopted similar algorithm to generate the diff it would work really well. In the extensions we ship we try to limit dependencies, so we only use it if it is already available in user's environment.

For perspective: With the test case files I shared. It takes black ~8 sec to format the file and return the formatted text. We then take that file and generate diffs (`difflib` takes about 363s, `levenshtein` takes about ~3s). the total time would be (diflib: ~370s, levelshtein: ~11s). Form discussions with team internally we felt that more than 1s to calculate the diff makes it feel slower than the tool itself. So, we time out at 1s and return the broad diff, from user point of view ~9s for that file.

For large files the experience will not be ideal the first time it is formatted, but any new formatting call on that file should result in narrow edits.

**Comment by konstin** [comment]
We can compute the diffs in rust which is near instead. I just checked that
```python
%timeit -n 1 -r 5 Levenshtein.editops(unformatted, formatted)
```
says
```
4.43 s ± 200 ms per loop (mean ± std. dev. of 5 runs, 1 loop each)
```
while 
```rust
use criterion::{black_box, criterion_group, criterion_main, Criterion};
use imara_diff::intern::InternedInput;
use imara_diff::{diff, Algorithm, UnifiedDiffBuilder};
use std::fs;

pub fn criterion_benchmark(c: &mut Criterion) {
    let unformatted = fs::read_to_string("sample.unformatted").unwrap();
    let formatted = fs::read_to_string("sample.py").unwrap();
    c.bench_function("diff sample", |b| {
        b.iter(|| {
            let input = InternedInput::new(unformatted.as_str(), formatted.as_str());
            black_box(diff(
                Algorithm::Myers,
                &input,
                UnifiedDiffBuilder::new(&input),
            ))
        })
    });
}

criterion_group!(benches, criterion_benchmark);
criterion_main!(benches);
```
takes 2ms. We currently have diff output, we could add `TextEdit` output.

Range editing is currently stalled for other projectsl, but i think we have to implement this inside the formatter anyway due to the syntax of line breaks and inserting/removing parentheses in python.
