### ISSUE TITLE
run ruff formatter on save in sublime

### ISSUE THREAD

**Issue by sryza** [astral-sh/ruff-lsp#293]
Ruff documentation includes recommendations on how run ruff to organize imports and auto-fix, inside Sublime Text.  I have gotten this working successfully.  But I'm having trouble doing the same Ruff's new auto-formatting.  Is there a way to do this?

I originally asked this on the sublime ruff LSP package (https://github.com/sublimelsp/LSP-ruff/issues/41), but they suggested that it might actually be a ruff-lsp issue.

Thanks for any help!

**Comment by dhruvmanila** [comment]
Closing this as resolved. Feel free to re-open or ask any additional questions. Happy formatting :)
