### ISSUE TITLE
support typeguard 4.x

### ISSUE THREAD

**Issue by billwanjohi** [astral-sh/ruff-lsp#299]
`ruff-lsp` currently depends on `pygls`, which does not yet have a version that supports `typeguard >=4.0.0`. This prevents me from installing this tool in a python environment that relies on newer versions of that library (e.g. `phantom-types >=2`).

Note that while #187 asserts that dropping Python 3.7 support blocks typeguard upgrade, the typeguard [version history](https://github.com/agronholm/typeguard/blob/master/docs/versionhistory.rst#version-history) and [commit log](https://github.com/agronholm/typeguard/commit/c6377206a2400f0616bf811ed8ccd3b77d9a1bf4) indicate that Python 3.7 is supported up to version 4.1.2, so this could plausibly be independently addressed.

---

A couple of workarounds I'm aware of:

- install `ruff-lsp` via a system package manager and the conflicting libraries only in individual virtual environments
  - this works until you have another binary that you want global access to
- install `ruff-lsp` via [pipx](https://pypa.github.io/pipx/), which provides isolated environments for each package under management
  - this works but is yet another tool to manage, for those who haven't already adopted it

**Comment by zanieb** [comment]
Thanks for the note regarding Python 3.7 and typeguard — I've updated that issue.

> pygls, which does not yet have a version that supports typeguard >=4.0.0

What can we do here then? Maybe I misunderstand you but if pygls does not support it then how can we resolve this issue?

**Comment by billwanjohi** [comment]
Yeah, I imagine the first step is opening an issue with `pygls`, to at least get a sense of their plans.

**Comment by zanieb** [comment]
I've resolved this upstream in https://github.com/openlawlibrary/pygls/pull/405, we'll bump our pygls and typeguard versions shortly.

**Comment by zanieb** [comment]
Should be resolved by https://github.com/astral-sh/ruff-lsp/pull/302

**Comment by billwanjohi** [comment]
Amazing!
