### ISSUE TITLE
conda-forge package

### ISSUE THREAD

**Issue by berceanu** [astral-sh/ruff-lsp#303]
Hi, I'm trying to create a conda-forge package for `ruff-lsp`. So far I've create a [PR](https://github.com/conda-forge/staged-recipes/pull/24390) with a draft recipe. Any support is appreciated, and feel free to add your names to the list of maintainers.

**Comment by moritzwilksch** [comment]
Awesome, I was just thinking about that! LMK if I can help

**Comment by berceanu** [comment]
You can add your name to the recipe-mainteners section, if you want :))
