### ISSUE TITLE
Missing dependency to python-packaging in the archlinux package

### ISSUE THREAD

**Issue by mpizenberg** [astral-sh/ruff-lsp#311]
Hi, I'm not sure where to report this, but when installing ruff-lsp in archlinux, it fails with the following error:

```
Traceback (most recent call last):
  File "/usr/bin/ruff-lsp", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/ruff_lsp/__main__.py", line 5, in main
    from ruff_lsp import __version__, server
  File "/usr/lib/python3.11/site-packages/ruff_lsp/server.py", line 55, in <module>
    from packaging.specifiers import SpecifierSet, Version
ModuleNotFoundError: No module named 'packaging'
```

Installing `extra/python-packaging` fixes that problem.

**Comment by konstin** [comment]
How did you install ruff-lsp?

**Comment by mpizenberg** [comment]
The `extra/ruff-lsp` package on archlinux.

**Comment by mpizenberg** [comment]
I just wanted to report the error here because it means whoever is packaging ruff-lsp for archlinux forgot to add a dependency to `extra/python-packaging`

**Comment by zanieb** [comment]
This should probably be reported over at https://archlinux.org/packages/extra/any/ruff-lsp/ instead but I believe the maintainers are @polyzen and @alerque

**Comment by charliermarsh** [comment]
Thanks @mpizenberg!

**Comment by polyzen** [comment]
Woops 🤭 Fixed now.

For issues with Arch Linux packaging, please follow https://wiki.archlinux.org/title/Bug_reporting_guidelines

**Comment by alerque** [comment]
Looks like Daniel beat me to it, but this issue can be closed as the fix went out already in a new package release.

**Comment by charliermarsh** [comment]
Thank you both!
