### ISSUE TITLE
Warning if a magic command is above the imports in a notebook

### ISSUE THREAD

**Issue by HenryDashwood** [astral-sh/ruff-lsp#328]
Ruff: 0.1.6
Ruff-VSCode: v2023.50.0

Currently Ruff complains if you have magic commands about the imports in a notebook. But for something like `autoreload`, I obviously want to run this before importing anything. 

Are there any plans to support this? Or is there a way to configure ruff to allow magic commands to be placed above the imports?

<img width="447" alt="image" src="https://github.com/astral-sh/ruff-lsp/assets/17177967/b57e6944-a14b-4224-8c33-b30c564e228a">

**Comment by dhruvmanila** [comment]
Hey, thanks for highlighting this issue. We're planning to fix this as part of https://github.com/astral-sh/ruff/issues/8669. I'll close this one in favor of that. This is probably the last rule which needs updating for Jupyter Notebook. That said, if you think there are any other rules, which aren't mentioned in the linked issue, that are worth updating for Jupyter Notebook, please do suggest :)
