### ISSUE TITLE
How to properly manage python import statements in my code

### ISSUE THREAD

**Issue by vgoklani** [astral-sh/ruff-lsp#334]
Hey there,

I'm using Ruff via `https://github.com/sublimelsp/LSP-ruff` in Sublime Text4 and these are my Ruff settings:

    // Settings in here override those in "LSP-ruff/LSP-ruff.sublime-settings"
    {
        "initializationOptions": {
            "globalSettings": {
                "lint.args": [
                    "--ignore",
                    "F401",
                ],
            },
        }
    }

This settings ignores unused imports. 

I would prefer that it highlights unused imports so that I can manually remove them.

I previously used `https://github.com/thep0y/python-black` which allowed this functionality.

Thanks!

**Comment by charliermarsh** [comment]
If you remove the `--ignore F401`, Ruff will highlight unused imports. Is the issue that you don't want Ruff to _remove_ them, only highlight them?

**Comment by vgoklani** [comment]
@charliermarsh yes, I want to highlight and manually remove them. Removing the `F401` automatically deletes them. Thanks!

**Comment by charliermarsh** [comment]
No prob. You can mark it as "flag, but don't fix" via:

```json
// Settings in here override those in "LSP-ruff/LSP-ruff.sublime-settings"
{
    "initializationOptions": {
        "globalSettings": {
            "lint.args": [
                "--unfixable",
                "F401",
            ],
        },
    }
}
```

**Comment by vgoklani** [comment]
Perfect, thank you!!!

**Comment by vgoklani** [comment]
last request, possible to automatically remove the trailing comma:

    from models.mistral.utils import (
        load_pretrained_model,
    )

if we manually remove the trailing comma, then it automatically fits on one line when hitting the save button

**Comment by charliermarsh** [comment]
Yeah! But not in your `LSP-ruff.sublime-settings`, you need to use a `pyproject.toml` or `ruff.toml` file, since we don't expose all settings on the command-line (and `LSP-ruff.sublime-settings` only supports passing command-line arguments).

You can add a `ruff.toml` to your project, with contents like:

```toml
unfixable = ["F401"]

[lint.isort]
split-on-trailing-comma = false

[format]
skip-magic-trailing-comma = true
```

If you want, you can also put that file _outside_ your project, and do something like:

```json
{
    "initializationOptions": {
        "globalSettings": {
            "lint.args": [
                "--config",
                "/path/to/ruff.toml",
            ],
            "format.args": [
                "--config",
                "/path/to/ruff.toml",
            ],
        },
    }
}
```

**Comment by vgoklani** [comment]
Wow that was amazing :) thank you!!

**Comment by charliermarsh** [comment]
No worries, always happy to help :)
