### ISSUE TITLE
kickstart.nvim code action difficulties

### ISSUE THREAD

**Issue by jturner116** [astral-sh/ruff-lsp#336]
Apologies if I have missed something obvious, I am trying to use Ruff more regularly but am not super experienced.

I've successfully installed `ruff-lsp` with Mason in kickstart neovim and am getting correct highlighting in Python files, but my Fix All code action does not seem to do anything. It doesn't remove trailing whitespace or address any of the other warnings. I have tried modifications to my init.lua found in other issues but haven't had any success with those either. 

running Ubuntu 22.04 WSL
Ruff version: 0.1.7
Mason setup from kickstart
```lua
require('mason').setup()
require('mason-lspconfig').setup()

-- Enable the following language servers
--  Feel free to add/remove any LSPs that you want here. They will automatically be installed.
--
--  Add any additional override configuration in the following tables. They will be passed to
--  the `settings` field of the server config. You must look up that documentation yourself.
--
--  If you want to override the default filetypes that your language server will attach to you can
--  define the property 'filetypes' to the map in question.
local servers = {
  -- clangd = {},
  -- gopls = {},
  -- pyright = {},
  rust_analyzer = {},
  ruff_lsp = {},
  -- tsserver = {},
  -- html = { filetypes = { 'html', 'twig', 'hbs'} },

  lua_ls = {
    Lua = {
      workspace = { checkThirdParty = false },
      telemetry = { enable = false },
      -- NOTE: toggle below to ignore Lua_LS's noisy `missing-fields` warnings
      diagnostics = { disable = { 'missing-fields' } },
    },
  },
}
```

**Comment by dhruvmanila** [comment]
Hey, if possible can you please provide some additional context? Like, Ruff configuration if any, Python code, the rule whose diagnostic is not being fixed (what diagnostic do you see?), etc.

**Comment by jturner116** [comment]
Of course, thanks for the quick response!

No ruff configuration, working from barebones install with kickstart. 

Here's the example I'm testing
![image](https://github.com/astral-sh/ruff-lsp/assets/59941858/880eae90-50d5-428c-b7d7-16f7eb435b89)

If I run ruff from command line, I can get it to fix the trailing whitespace, but the code action doesn't. The imports code action is working though, do I need to alter the config to allow Fix All to address whitespace?
