### ISSUE TITLE
Typo in README (Settings)

### ISSUE THREAD

**Issue by mschreil** [astral-sh/ruff-lsp#367]
Seems there is a Typo in the README Settings. 
https://github.com/astral-sh/ruff-lsp/blob/main/README.md?plain=1#L254

Is it `line.enable` or should it be `lint.enable`

**Comment by MichaReiser** [comment]
It's `lint.enable`. Do you want to PR the change to fix the setting name?

**Comment by charliermarsh** [comment]
Oops, thank you! Fixed!
