### ISSUE TITLE
How to use ruff-lsp along with pyright in Neovim

### ISSUE THREAD

**Issue by pratyushmittal** [astral-sh/ruff-lsp#384]
Ruff-LSP handles most of the things. I want to use `pyright` only for things which `ruff-lsp` doesn't do. **I am unable to disable `pyright` for things which `ruff-lsp` already does.**

The `README` and documentation mentions about using `ruff-lsp` with another `lsp`:

> Note that if you're using Ruff alongside another LSP (like Pyright), you may want to defer to that LSP for certain capabilities, like textDocument/hover

How do we disable `pyright` for linting and formatting?

I read through all existing issues but couldn't find a complete configuration of using `pyright` along with `ruff`.

I am using this configuration, but it does linting using both `pyright` and `ruff`.

```
local lspconfig = require('lspconfig')
local on_attach = function(client, bufnr)
    -- Disable hover in favor of Pyright
    client.server_capabilities.hoverProvider = false
end
lspconfig.ruff_lsp.setup {
    on_attach = on_attach,
    init_options = {
        settings = {
            -- Any extra CLI arguments for `ruff` go here.
            args = {},
        }
    }
}
lspconfig.pyright.setup {
    settings = {
        python = {
            analysis = {
                -- warnings in factory boy for meta class overide
                typeCheckingMode = "basic"
            }
        }
    }
}
```

Please share your config if anyone has been able to use `pyright` along with `ruff-lsp` without the overlaps.

**Comment by dhruvmanila** [comment]
Hey, thanks for using Ruff!

> How do we disable `pyright` for linting and formatting?

Well, I just figured out how to disable diagnostics in Pyright, thanks! You can put the following in your config which disables linting, import sorting and type checking from Pyright and thus only provides completions, goto(s), etc.

```lua
  pyright = {
    settings = {
      pyright = {
        disableOrganizeImports = true, -- Using Ruff
      },
      python = {
        analysis = {
          ignore = { '*' }, -- Using Ruff
          typeCheckingMode = 'off', -- Using mypy
        },
      },
    },
  }
```

I'll document this in the README.

**Comment by pratyushmittal** [comment]
Thanks a lot @dhruvmanila. It works!

**Comment by horta** [comment]
@dhruvmanila  Thank you!!!! Related to: https://github.com/neovim/nvim-lspconfig/issues/726

**Comment by StitiFatah** [comment]
> Hey, thanks for using Ruff!
> 
> > How do we disable `pyright` for linting and formatting?
> 
> Well, I just figured out how to disable diagnostics in Pyright, thanks! You can put the following in your config which disables linting, import sorting and type checking from Pyright and thus only provides completions, goto(s), etc.
> 
> ```lua
>   pyright = {
>     settings = {
>       pyright = {
>         disableOrganizeImports = true, -- Using Ruff
>       },
>       python = {
>         analysis = {
>           ignore = { '*' }, -- Using Ruff
>           typeCheckingMode = 'off', -- Using mypy
>         },
>       },
>     },
>   }
> ```
> 
> I'll document this in the README.

For me it seems that ```  analysis = {
          ignore = { '*' }, 
}

```
also disables typing, how would one let ruff manage linting etc but let pyright provide typing errors ?

**Comment by steakhutzeee** [comment]
Hi, as mentioned above by @StitiFatah is it possible to preserve pyright's typing?

**Comment by dhruvmanila** [comment]
Unfortunately, I don't think it's possible to _just_ enable type checking for Pyright and disable other diagnostics. One would need to manually go through the list of diagnostics supported by Pyright (https://github.com/microsoft/pyright/blob/main/docs/configuration.md#type-check-diagnostics-settings) and disable the ones which overlaps with Ruff's rules.

**Comment by StitiFatah** [comment]
After using mypy for a bit instead of pyright for diagnostics I feel that mypy miss a lot of things pyright doesn't.
Since it's not possible to cherry pick I've removed mypy and also ` python = {
            analysis = {
              -- Ignore all files for analysis to exclusively use Ruff for linting
              -- ignore = { "*" },
            },
`
and added this (which i found [here](https://www.reddit.com/r/neovim/comments/11k5but/comment/jbjwwtf/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)) to my `lspconfig` configuration ` servers = {
        pyright = {
          capabilities = (function()
            local capabilities = vim.lsp.protocol.make_client_capabilities()
            capabilities.textDocument.publishDiagnostics.tagSupport.valueSet = { 2 }
            return capabilities
          `end)(),`

Fwiw it seems to fix duplicates like `subprocess imported but not used` from Ruff  and `"subprocess" is not accessed` by removing Pyright's ones while still benefiting from its type diagnostics.

**Comment by dhruvmanila** [comment]
Thanks for the suggestion!

**Comment by steakhutzeee** [comment]
To me this is still duplicating stuff.

![Screenshot 2024-03-12 105920](https://github.com/astral-sh/ruff-lsp/assets/57228102/b4cb8e16-a91b-465f-8c97-2f1a099edc93)

**Comment by benedikt-bartscher** [comment]
@steakhutzeee are you by any chance using kickstart.nvim?  If so, try this:
```lua
    require('mason-lspconfig').setup {
      handlers = {
        function(server_name)
          local server = servers[server_name] or {}
          server.capabilities = vim.tbl_deep_extend('force', {}, capabilities, server.capabilities or {})
          -- https://github.com/astral-sh/ruff-lsp/issues/384#issuecomment-1989619482
          if server_name == 'pyright' then
            server.capabilities.textDocument.publishDiagnostics.tagSupport.valueSet = { 2 }
          end
          require('lspconfig')[server_name].setup(server)
        end,
      },
    }
```

**Comment by StitiFatah** [comment]
Well it seems that there are still duplicates, from my current understanding the settings above only remove what they call "hints" https://github.com/microsoft/pyright/discussions/3929#discussioncomment-5434231 

Errors like those for undefined variables are still emitted by both Pyright and Ruff. (as pointed by a message above ehich seems to have been deleted)

Those pyright errors are documented [here](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#type-check-diagnostics-settings) but I couldn't figure out where to place them in my nvimlsconfig.lua, I've tried under each table but nothing worked, maybe it's only possible to use them in `pyproject.toml` ot `pyrightconfig.json`, the latter works for me but it'd be cumbersome to define those for each project and would be problematic for scripts too, and there is apparently [no way to set those in a global way](https://github.com/microsoft/pyright/issues/176#issuecomment-513964753). 

So for now I'm settling with  disabling those duplicates from the Ruff side. For undefined variables for example one would do : 

```

ruff_lsp={
        init_options = {
          settings = {
            args = {
              "--ignore=F821",
            },
          },
        },

}
```
It'd be helpful if we could document duplicates somewhere since pyright + ruff seems like a popular combo.

**Comment by StitiFatah** [comment]
> My lspconfig actually includes:
> 
> ```
> function M.common_capabilities()
>   local status_ok, cmp_nvim_lsp = pcall(require, "cmp_nvim_lsp")
>   if status_ok then
>     return cmp_nvim_lsp.default_capabilities()
>   end
> 
>   local capabilities = vim.lsp.protocol.make_client_capabilities()
>   capabilities.textDocument.completion.completionItem.snippetSupport = true
>   capabilities.textDocument.completion.completionItem.resolveSupport = {
>     properties = {
>       "documentation",
>       "detail",
>       "additionalTextEdits",
>     },
>   }
>   capabilities.textDocument.foldingRange = {
>     dynamicRegistration = false,
>     lineFoldingOnly = true,
>   }
> 
>   return capabilities
> end
> ```
> 
> How could I include this change?

If you're using the `lazy.nvim` package manager you could have a look at my [config](https://github.com/StitiFatah/DotFiles/blob/master/nvim/.config/nvim/lua/plugins/nvimlspconfig.lua).
Bear in mind that I'm also using `LazyVim` (the distro), so things are getting merged with the default config which is [here](https://www.lazyvim.org/plugins/lsp#mason-lspconfignvim)

**Comment by steakhutzeee** [comment]
> > My lspconfig actually includes:
> > ```
> > function M.common_capabilities()
> >   local status_ok, cmp_nvim_lsp = pcall(require, "cmp_nvim_lsp")
> >   if status_ok then
> >     return cmp_nvim_lsp.default_capabilities()
> >   end
> > 
> >   local capabilities = vim.lsp.protocol.make_client_capabilities()
> >   capabilities.textDocument.completion.completionItem.snippetSupport = true
> >   capabilities.textDocument.completion.completionItem.resolveSupport = {
> >     properties = {
> >       "documentation",
> >       "detail",
> >       "additionalTextEdits",
> >     },
> >   }
> >   capabilities.textDocument.foldingRange = {
> >     dynamicRegistration = false,
> >     lineFoldingOnly = true,
> >   }
> > 
> >   return capabilities
> > end
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > How could I include this change?
> 
> @steakhutzeee If you're using the `lazy.nvim` package manager you could have a look at my [config](https://github.com/StitiFatah/DotFiles/blob/master/nvim/.config/nvim/lua/plugins/nvimlspconfig.lua). Bear in mind that I'm also using `LazyVim` (the distro), so things are getting merged with the default config which is [here](https://github.com/neovim/nvim-lspconfig)

I'm using this configuration basically https://github.com/ChristianChiarulli/nvim/blob/master/lua/user/lspconfig.lua

As you can see the capabilities are already defined there. And he configured the servers in a separate dir https://github.com/ChristianChiarulli/nvim/tree/master/lua/user/lspsettings

So you think there is a way to add the settings in the lsp config or in a dedicated file separately?

**Comment by StitiFatah** [comment]
I cant guarantee it but my guess is that it'd overwrite the main `  `neovim/nvim-lspconfig` configuration. But you could easily add those `local opts = {
      on_attach = M.on_attach,
      capabilities = M.common_capabilities(),
    }` to your own individual config files and merge it with your own options including capablities. 

Or you could let them in this file, and do like he did with the lua lsp with a `    `if server == "pyright"` and merge your own options to the `opts` here

**Comment by tuan-h** [comment]
you can do this to use pyright with ruff_lsp and ignore pyright's diagnostics to avoid duplicates (but you have to disable them one by one) while still keeping pyright's type checking:

```lua
settings = {
    pyright = {
      disableOrganizeImports = true, -- Using Ruff
      disableTaggedHints = true,
    },
    python = {
      analysis = {
        diagnosticSeverityOverrides = {
          -- https://github.com/microsoft/pyright/blob/main/docs/configuration.md#type-check-diagnostics-settings
          reportUnusedImport = "none",
          reportUndefinedVariable = "none",
        },
      },
    },
  },

```

**Comment by GraphtyLove** [comment]
> you can do this to use pyright with ruff_lsp and ignore pyright's diagnostics to avoid duplicates (but you have to disable them one by one) while still keeping pyright's type checking:
> 
> settings = {
>     pyright = {
>       disableOrganizeImports = true,
>       disableTaggedHints = true,
>     },
>     python = {
>       analysis = {
>         diagnosticSeverityOverrides = {
>           -- https://github.com/microsoft/pyright/blob/main/docs/configuration.md#type-check-diagnostics-settings
>           reportUndefinedVariable = "none",
>         },
>       },
>     },
>   },

This should be documented in the README.
It's pretty confusing..

**Comment by pratyushmittal** [comment]
@GraphtyLove It is now documented here: https://docs.astral.sh/ruff/editors/setup/#neovim

**Comment by biaojiang** [comment]
> you can do this to use pyright with ruff_lsp and ignore pyright's diagnostics to avoid duplicates (but you have to disable them one by one) while still keeping pyright's type checking:
> 
> settings = {
>     pyright = {
>       disableOrganizeImports = true,
>       disableTaggedHints = true,
>     },
>     python = {
>       analysis = {
>         diagnosticSeverityOverrides = {
>           -- https://github.com/microsoft/pyright/blob/main/docs/configuration.md#type-check-diagnostics-settings
>           reportUndefinedVariable = "none",
>         },
>       },
>     },
>   },

Still not working well by adding `diagnosticSeverityOverrides`. The configurations of Ruff alongside Pyright were specified here: https://docs.astral.sh/ruff/editors/setup/#neovim, but `ignore = { '*' }` didn't work, so I have to use `Pyright` only and use `Ruff cli` on save.

**Comment by 513G3** [comment]
I hope someone can take this fact and turn it into a proper bug report.

I figured out that if you have a Pyright `root_marker` in place (even an empty one), `ignore = { “*” }` works.

Ex:
`$ touch pyproject.toml`

See: https://github.com/513G3/kickstart-modular.nvim/commit/d2292aaa8c1ffa0de32b93886f3a55b547cc2ec2
