### ISSUE TITLE
Update readme for helix

### ISSUE THREAD

**Issue by luccahuguet** [astral-sh/ruff-lsp#389]
Firstly, it's amazing that such a cool project has a dedicated session for helix. Exciting stuff.

On to the issue: The helix example on the readme is now a bit outdated

because you can already use multiple language servers as of 23.10 (https://helix-editor.com/news/release-23-10-highlights/)

so the example becomes something like

```
[[language]]
name = "typescript"
auto-format = true
language-servers = [
  { name = "efm", only-features = ["format", "diagnostics"] },
  { name = "typescript-language-server", except-features = ["format", "diagnostics"] },
]
```

**Comment by charliermarsh** [comment]
Thank you! I'd be happy to merge a PR with these updates, any interest?

**Comment by luccahuguet** [comment]
> Thank you! I'd be happy to merge a PR with these updates, any interest?

it would be an honor, haha

I'll get to it
