### ISSUE TITLE
Ruff-lsp fails to initialise on vscode remote-ssh

### ISSUE THREAD

**Issue by EricDepagne** [astral-sh/ruff-lsp#412]
Hi.
I'm using ruff and ruff-lsp on an official vscode running on a mac.
The ruff-lsp fails to start when using the Remote-ssh extension. the remote machine is running Debian 11.
When I activate the ruff extension remotely, I get the following message:

> 2024-03-22 12:39:12.629 [info] [Error - 12:39:12 PM] Ruff client: couldn't create connection to server.
> 2024-03-22 12:39:12.629 [info] Error: Unsupported server configuration {
>     "args": [
>         "/home/XXX/.vscode-server/extensions/charliermarsh.ruff-2024.16.0/bundled/tool/server.py"
>     ],
>     "options": {
>         "cwd": "/home/XXX/YYY/ZZZ",
>         "env": {
> [snip]
>          }
>      }
> }
> 	at /home/XXX/.vscode-server/extensions/charliermarsh.ruff-2024.16.0/dist/extension.js:1:304647
> 	at async b.createConnection (/home/XXX/.vscode-server/extensions/charliermarsh.ruff-2024.16.0/dist/extension.js:1:139961)
> 	at async b.start (/home/XXX/.vscode-server/extensions/charliermarsh.ruff-2024.16.0/dist/extension.js:1:130476)
> 	at async t.restartServer (/home/XXX/.vscode-server/extensions/charliermarsh.ruff-2024.16.0/dist/extension.js:1:54104)
> 	at async S (/home/XXX/.vscode-server/extensions/charliermarsh.ruff-2024.16.0/dist/extension.js:1:391538)
> 	at async /home/XXX/.vscode-server/extensions/charliermarsh.ruff-2024.16.0/dist/extension.js:1:392090
> 2024-03-22 12:39:12.629 [error] Server: Start failed: Error: Unsupported server configuration {
> And the same content as earlier

I tried to delete the extension and reinstall it, to no avail.
I suspect there is a config file left somewhere, that I can't find, that has some options wrong.
I suspect the wrong option is the cwd, as I'm not even activating the extention in the /home/XXX/YYY/ZZZ/ directory.

But I was not able to find any configuration file that had it, so I'm a bit lost.

Any help appreciated.
Thank you.

**Comment by MichaReiser** [comment]
This seems related to https://github.com/astral-sh/ruff-vscode/issues/240
