### ISSUE TITLE
Why can't ruff-lsp check for E30* errors even if I add the --preview parameter?

### ISSUE THREAD

**Issue by a1401358759** [astral-sh/ruff-lsp#413]
Why can't ruff-lsp check for E30* errors even if I add the `--preview` parameter?
![image](https://github.com/astral-sh/ruff-lsp/assets/15830146/2cbe95d0-cd1b-47e7-bb4f-21e154a990b1)

**Comment by MichaReiser** [comment]
I think the problem is that Ruff, by default, only enables the `E4`, `E7`, `E9`, and `F` rules. That means you need to change your configuration to also enable `E3` in addition to enabling preview mode:

```
args = {
	"--preview",
	"--ingore=E402,E501",
	"--line-length=120",
	"--extend-select=E3"
}
```

**Comment by a1401358759** [comment]
@MichaReiser Thank you very much for your answer, it works!
