### ISSUE TITLE
How to configure sign icons

### ISSUE THREAD

**Issue by tall-josh** [astral-sh/ruff-lsp#421]
Hi, I'm wondering if I'm able to configure the _sign icons_ that appear in the left margin that indicate `warning|error|hint|info`?

I'm using `init.lua`, my previous config when using `lsp-zero` was 

```lua
lsp.set_sign_icons({
  error = "W",
  warning = "X",
  hint = "Y",
  info = "Z",
})
```

**Comment by MichaReiser** [comment]
I don't think I'm able to help you with this without knowing more about your setup. What editor are you using? Anyway, I think this is an editor and not an LSP feature.

**Comment by dhruvmanila** [comment]
Yeah, it is an editor related query. Neovim's LSP client uses the builtin diagnostic system to display any violations so you might want to look at that part of the documentation, especially the [`vim.diagnostic.Opts.Signs`](https://neovim.io/doc/user/diagnostic.html#vim.diagnostic.Opts.Signs). I'll close this issue.
