### ISSUE TITLE
Ruff-LSP wrongly categorized on Mason

### ISSUE THREAD

**Issue by baco** [astral-sh/ruff-lsp#437]
Ruff version in `ruff-lsp`, installed via Mason: `0.4.5`

Ruff-LSP only offers linting/formatting, but does not provide the most useful features of an LSP server; it doesn't offer neither completion, nor type-validation.

Instead of being categorized as LSP, it should be categorized as Linter.
![image](https://github.com/astral-sh/ruff-lsp/assets/102958/5d60af64-096d-4240-b08d-f85398bca457)

**Comment by zanieb** [comment]
Hi! We don't maintain the entry in the Mason registry, but a casual search brings up https://github.com/mason-org/mason-registry/pull/5183 — maybe you should open an issue over there if you think this categorization is incorrect?

**Comment by zanieb** [comment]
Happy to chime in on any issue you create if there are questions about Ruff's LSP capabilities.
