### ISSUE TITLE
Feature Request | Using ruff-lsp for VSCode

### ISSUE THREAD

**Issue by SnirShechter** [astral-sh/ruff-lsp#438]
Is it possible for ruff-lsp to fully replace Pylance on VSCode? I opened a similar feature request on vscode-python [here](https://github.com/microsoft/vscode-python/issues/23498).

**Comment by MichaReiser** [comment]
Not today. We have plans to build more LSP features other than linting and formatting in the future (e.g. semantic highlighting, type checking, auto completion) but that's going to take some time.

**Comment by Erik262** [comment]
@MichaReiser any progress at LSP for listing, formatting, highlighting, type checking, etc., so far? That would be a real big deal for many people who are waiting to get rid of Pylance and using Ruff as the way to go.
