### ISSUE TITLE
Unable to see ruff CodeActions

### ISSUE THREAD

**Issue by AnirudhG07** [astral-sh/ruff-lsp#482]
I just downloaded the ruff-lsp in my Neovim. I am able to see formatting, sorting of imports, linting, etc. But i am unable to see CodeActions as the snippets provides(as it says it will automatically come)...

Can you help me? Here is my link to neovim LSP [dotfiles](https://github.com/AnirudhG07/dotfiles/tree/ugcl/nvim/.config/nvim/lua/anirudh/plugins/lsp).

Version ruff: v0.6.1
Ruff should work anywhere on my machine, so i have not made any ruff.toml, using whatever is made(if made, not sure) by default.

**Comment by AnirudhG07** [comment]
Also is there no `:Ruff` option or similar  i can use. If it exists, pls share. If not, it would be great if you could make that for neovim.

**Comment by dhruvmanila** [comment]
Hey,

We now recommend to use the native server (not `ruff-lsp`) for which you can find the setup docs at https://docs.astral.sh/ruff/editors/setup/#neovim for Neovim. It's implemented within Ruff itself so you don't need to install a separate package. If you've `ruff` binary installed, then the server is available to you and you just need to configure `nvim-lspconfig` to do that.

Looking at your dotfiles, you'd just need to change `ruff_lsp` to `ruff` (https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#ruff).

**Comment by AnirudhG07** [comment]
Hi. thanks for your fast response. i have change `ruff_lsp` to `ruff`. I am still now getting Code Actions. The behaviour didnt change. Can you explain me how to get it please?

**Comment by AnirudhG07** [comment]
Also i saw [this](https://github.com/yaegassy/coc-ruff?tab=readme-ov-file). Seems very elegant to me. Is this for only coc.nvim or can be used in general?

**Comment by dhruvmanila** [comment]
You'd need to ask the server for the code action which can be done by `vim.lsp.buf.code_action` (https://neovim.io/doc/user/lsp.html#vim.lsp.buf.code_action()).

**Comment by AnirudhG07** [comment]
There is an issue with ruff.
Ruff made my python code working VERY slow. Like when I press `:`, it would take 5-6 seconds to just open it.
for small files it worked fine, but for bigger files, it was very slow. 
I switched back to previous ones, which we black, pylint, etc. and the speed came back for python. 

I initially thought something was wrong with my neovim. so I reinstalled it, restarted my comp but the issue for slowness persisted. As mentioned above, when I removed ruff from LSP, the speed of general neovim commands came back. Please look into it.

**Comment by dhruvmanila** [comment]
> Ruff made my python code working VERY slow. Like when I press `:`, it would take 5-6 seconds to just open it.
> for small files it worked fine, but for bigger files, it was very slow.

What would take that much time to open? Are you referring to the completion for the Neovim commands?

Regardless, this seems unlikely to be caused by Ruff because we don't support autocompletion.

Is your original issue resolved about code actions?

**Comment by AnirudhG07** [comment]
Yes code actions is taken care of. Thanks for the reference!
