### ISSUE TITLE
Server is showing outdated syntax errors

### ISSUE THREAD

**Issue by vikigenius** [astral-sh/ruff-lsp#495]
I filed an issue report on emacs-lsp but I was wondering if this is a ruff-issue because I only started seeing it after 0.0.54

Syntax-errors show up as I type but don't go away after I save. I have to restart the server for them to go away.

https://github.com/emacs-lsp/lsp-mode/issues/4547

**Comment by vikigenius** [comment]
I think the issue is that Emacs lsp-mode switched their client to ruff server instead of ruff-lsp. So the issue could be on their side or could be with ruff server.

So it probably doesn't belong here. I am going to create an issue on the ruff repo instead

**Comment by MichaReiser** [comment]
Hi @vikigenius 

I'm not using emacs myself but I gave it a quick try in VS code and lint and syntax diagnostics correctly refresh when I type. 

Do you observe this issue only with syntax or both for syntax and lint errors?

One difference between `ruff-lsp` and ruff server is that the latter uses pull diagnostics when available. Maybe emacs-lsp isn't pulling the new diagnostics as you type?

**Comment by vikigenius** [comment]
@MichaReiser you can follow the discussion on the linked issue. But here are the IO logs between the server and client

[ruff-io-log.txt](https://github.com/user-attachments/files/17037006/ruff-io-log.txt)

Does this seem right to you?

**Comment by MichaReiser** [comment]
I'll comment in the linked issue so that the entire conversation happens in one place.

**Comment by MichaReiser** [comment]
Note: This is a bug in ruff server and not ruff lsp but I don't think it's worth moving the issue now where it is already linked in several places.
