### ISSUE TITLE
Support for Kate

### ISSUE THREAD

**Issue by KhazAkar** [astral-sh/ruff-lsp#89]
Hi!
I just wanted to drop here a simple question – did anybody managed to wire ruff-lsp with Kate editor? It does have support for LSP, but I have no idea how to wire ruff-lsp up.
Editor in question: [Kate](https://kate-editor.org/) 

Thanks,
Damian

**Comment by Ekopalypse** [comment]
Something like this works for me

![image](https://user-images.githubusercontent.com/47723516/226969293-aaa1fdb8-4022-4a22-b9cc-45665e3e0f49.png)

below the config for easy copy/paste

~~~json
{
    "servers": {
        "python": {
            "command": ["PATH_TO/ruff-lsp.exe"],
            "url": "https://github.com/charliermarsh/ruff-lsp",
            "highlightingModeRegex": "^Python$"
        }
    }
}
~~~
