### ISSUE TITLE
No code actions available when hovered over certain warnings

### ISSUE THREAD

**Issue by patrickarmengol** [astral-sh/ruff-lsp#94]
When hovering over certain warnings, like F401, no code actions are available. This seems to be unintended as the first example gif in the readme (https://github.com/charliermarsh/ruff-lsp#quick-fix-actions-for-auto-fixable-violations-like-unused-imports) shows available code actions when hovering F401. 

Environment: neovim 0.9.0, ruff-lsp 0.0.24

Steps to reproduce:
1. Open a python file
2. Scroll over or write in an unused import to create a F401 warning. 
3. Try to call code actions `:lua =vim.lsp.buf.code_action()`

![screenshot](https://user-images.githubusercontent.com/42473149/232255165-eb2becf1-554d-4511-8cf1-d447d529cfe0.png)

Another diagnostic code that causes this issue is F821(undefined name). Per https://github.com/charliermarsh/ruff-lsp/issues/91#issuecomment-1507472357 this may affect quite a few more types of warnings.

**Comment by charliermarsh** [comment]
I just tested this locally in Neovim and it worked correctly for me with `v0.8.1`, AFAICT:

<img width="868" alt="Screen Shot 2023-04-22 at 7 36 48 PM" src="https://user-images.githubusercontent.com/1309177/233811960-2dabc502-a4d7-4663-8e21-843678666670.png">

I'll try upgrading to 0.9.0.

**Comment by charliermarsh** [comment]
Hmm, ok, still seems to work on 0.9.0. Do you have other plugins installed, anything else that could be impacting this?

**Comment by patrickarmengol** [comment]
> Hmm, ok, still seems to work on 0.9.0. Do you have other plugins installed, anything else that could be impacting this?

Not sure what it could be. I disabled pyright that was running beside it. I commented out the ruff-lsp lines from lspconfig. 

Just to give some background, I'm running [astronvim](https://github.com/AstroNvim/AstroNvim). The base config files for lsp stuff ([utils/lsp.lua](https://github.com/AstroNvim/AstroNvim/blob/main/lua/astronvim/utils/lsp.lua) and [plugins/configs/lspconfig.lua](https://github.com/AstroNvim/AstroNvim/blob/main/lua/plugins/configs/lspconfig.lua)) don't seem to reveal anything that could be causing this (at least to my eyes). 

Another user on the astronvim discord reported the same issue too, so perhaps it's an "us" problem. 
![screenshot](https://user-images.githubusercontent.com/42473149/233812749-d05aa594-d78b-4141-ad2f-e9c93ae7b1ab.png)

Though I wonder why https://github.com/charliermarsh/ruff-lsp/issues/91#issuecomment-1507472357 ran into the same problem. 

I'll try to mess around a bit more to isolate it.

**Comment by patrickarmengol** [comment]
Ok, looks like I messed up when choosing an example warning to represent the issue as `F401` was marked under `unfixable` in the ruff settings for the default hatch-generated `pyproject.toml`. 

Still, this occurs for other warnings like:

F821 (undefined name)
![screenshot](https://user-images.githubusercontent.com/42473149/234437634-0f9029f0-bf17-45b1-b8da-66b3516514c4.png)

F704 (yield outside function):
![screenshot](https://user-images.githubusercontent.com/42473149/234437826-0d872e05-1ebf-485f-bca1-508e1031e9bb.png)

**Comment by charliermarsh** [comment]
Ah no worries. I think those two errors aren't actually fixable though, so it seems right for there to be no code actions available.

**Comment by patrickarmengol** [comment]
> Ah no worries. I think those two errors aren't actually fixable though, so it seems right for there to be no code actions available.

Should file-wide actions (like fix-all and org-imports) still be unavailable though? They are available on empty lines and other fixable warnings. Sorry I'm not sure how code actions for other LSPs usually work.

**Comment by charliermarsh** [comment]
Oh, hmm, maybe? I'd say yes? But I'm not 100% certain either, it could vary from client to client, but I'm confused as to why it would suppress them there.

**Comment by patrickarmengol** [comment]
I'm coming from VSCode, where the actions are available in such situations, so I thought it was strange. Also ran into it when testing out performing code actions on save in order to auto-sort imports in nvim. IMO they should be available, but it's your call. Feel free to close this issue.

**Comment by burnettk** [comment]
I took the time to create a minimal repro for an issue that I saw that may be an example of this: https://github.com/burnettk/assorted-repro-scenarios/tree/main/ruff-lsp-bug-repro. Basically, with the following code, even though there are linting issues on both lines. there are no code actions for line 1, but there are code actions for line 2:

```` python
def sureEnough():
    a = 1
    print("I'm sure")

sureEnough()
````

**Comment by dhruvmanila** [comment]
I'm pretty confident it's the same issue: https://github.com/astral-sh/ruff-lsp/issues/128

It should be fixed on HEAD. Let me give a quick test with the examples mentioned in the issue. @charliermarsh we would probably need to make a patch release.

**Comment by dhruvmanila** [comment]
Yeah, it's the same issue. It's fixed with https://github.com/astral-sh/ruff-lsp/pull/129
